name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Git for GitHub Pages
        run: |
          git config --global user.name "Parag Yelonde"
          git config --global user.email "parag.yelonde159@gmail.com"


