# .github/workflows/main.yml

name: Main Python CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  build:
    name: Build and Run Script  # Name of the job
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set Python version to 3.9

      - name: Install dependencies
        run: |
          echo "No dependencies to install"  # If you had dependencies, install them here.

      - name: Run Hello World Python script
        run: python hello_world.py  # Run the Python script

      - name: Display Committer Information
        run: |
          echo "This workflow was triggered by: ${{ github.actor }}"  # Display the user who triggered the workflow
          echo "Commit URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"  # Link to commit

