name: CI/CD Pipeline for HTML

on:
  push:
    branches:
      - main   # Trigger on push to main branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use a specific Node.js version (optional, in case you need npm)

      - name: Install dependencies (Optional)
        run: |
          npm install  # If you have any dependencies (like using Parcel or Webpack for a build)

      - name: Build project (Optional)
        run: |
          npm run build   # If you're using a build tool like Webpack or Parcel

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "parag.yelonde159@gmail.com"
          git config --global user.name "Parag Yelonde"
          git remote set-url origin https://github.com/${{ github.repository }}
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy updates"
          git push --force origin gh-pages


