# .github/workflows/test.yml

name: Python Test Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  test:
    name: Test Job  # Name of the job
    runs-on: ubuntu-latest  # Run on the latest Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set Python version to 3.9

      - name: Install dependencies
        run: |
          echo "No dependencies to install"  # Install dependencies if needed

      - name: Run Unit Tests
        run: |
          python -m unittest discover  # Discover and run all tests in the repository

